version: "3"

services:
  line-speech-bot:
    build: .
    container_name: line-speech-bot
    image: line-speech-bot:latest
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Asia/Bangkok
      VIRTUAL_HOST: linebot.cocoa-d.net 
      LETSENCRYPT_HOST: linebot.cocoa-d.net
      LETSENCRYPT_EMAIL: support@cocoa-d.net
    networks:
      - nginx-proxy-cocoad

networks:
  nginx-proxy-cocoad:
    external: true
